name: HL7 Validator
description: Run the HL7 Java validator and analyze the results.
inputs:
  ig:
    description: An IG or profile definition to load
    default: "none"
  recurse:
    description: Look in subfolders when -ig refers to a folder
    default: "true"
  tx:
    description: The [base] url of a FHIR terminology server
    default: "none"
  profile:
    desciption: the canonical URL to validate against
    default: "none"
  language:
    description: The language to use when validating coding displays - same value as for xml:lang
    default: "none"
  source:
    description: a file, url, directory or pattern for resources to validate
    required: true
  allow-level:
    description: The level from which issues are considered not fatal (0 = error, 1 warning, 2 = information)
    default: 1
runs:
  using: docker
  image: Dockerfile
  args:
    - -i ${{ inputs.ig }}
    - -r ${{ inputs.recurse }}
    - -t ${{ inputs.tx }}
    - -p ${{ inputs.profile }}
    - -l ${{ inputs.language }}
    - -a ${{ inputs.allow-level }}
    - ${{ inputs.source }}
